name: smsbolt
description: "Une application pour traiter les SMS de transactions mobile money"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  http: ^1.1.2
  google_generative_ai: ^0.2.0
  flutter_riverpod: ^2.4.9
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
